### ISSUE TITLE
Version 4.0.0 - Release

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/issues#16]
This issue is to track what goes into the version 4.0.0 release. Please document public API changes here to keep track of them.

Current breaking changes:

- In `@podium/client` the `.fetch()` method returns an object instead of a plain string.
- In `@podium/utils` and `@podium/podlet` the `.view()` method takes a template with a different characteristic.

Current deprecations:

 - In `@podium/client` on the `.stream()` method, the `headers` event should be deprecated.
 - In `@podium/client` the `change` event should be deprecated.
 - In `@podium/client` the `dispose` event should be deprecated.
 - In `@podium/schema` the `assets` property is deprecated.

**Comment by trygve-lie** [comment]
In `@podium/client` changes to the `.fetch()` and `.stream()` methods (https://github.com/podium-lib/client/pull/23):

The `.fetch()` method did previously just resolve with a `String` where the `String` is the content of the podlet it fetched. This is now changed so the `.fetch()` method resolves with an `object` (**BREAKING CHANGE**) containing the content, css and js for the podlet:

```js
podlet
    .fetch()
    .then(data => {
        console.log(data.content);
        console.log(data.js);
        console.log(data.css);
    })
    .catch(error => {
        console.log(error);
    });
```

The `.stream()` method  has gotten a `beforeStream` event emitting an object with js, css, and headers values:

```js
const stream = component.stream();
stream.once('beforeStream', data => {
    console.log(data.headers);
    console.log(data.js);
    console.log(data.css);
});
```

**TODO:** 

- We should try to get `.fetch()` backwards compatible with an deprecation warning (@trygve-lie  has a potential solution).
- We should deprecate the `headers` event on the `.stream()` method.

**Comment by digitalsadhu** [comment]
In `@podium/utils`

* a `.template()` method has been added so that we can share this template in both the podlet and the layout
* `.view()` now accepts a template function with a different shape (**BREAKING CHANGE**)

```js
const template = ({ head, title, encoding, locale, js, css, body }) => `...`;
```

* the `HttpIncoming` `.render()` now accepts either a string (as before) or an object (which matches the new template syntax. This is a backwards compatible change.
* `HttpIncoming` now has a `.proxy` property which the `@podium/proxy` module can use to indicate that it has (or has not) handled a request as a proxy request.

**Comment by digitalsadhu** [comment]
In `@podium/podlet`

* development template removed, shared template in `@podium/utils` is now being used instead
* bug fix to use `.js()` and `.css()` methods instead of `.jsRoute` and `.cssRoute` internally in process method.
* `.render()` method added that can be used by framework implementors (express, hapi, serverless etc)

```js
const incoming = new HttpIncoming(req, res, res.locals);
const result = podlet.render(incoming, '<div>some content to render</div>');
```

* `.middleware()` method changed to use new `.render()` method
* `.middleware()` method refactored to use async/await
* `.middleware()` method refactored to use the new `httpIncoming.proxy` flag
* `.view()` method uses updated version of `@podium/utils` > `HttpIncoming` > `.view()` method which requires a different template syntax to be used (**BREAKING CHANGE**)

**Comment by digitalsadhu** [comment]
In `@podium/layout`

* `.css()` method added to match podlet and set own css

```js
layout.css({ value: `http://cdn.com/abc123abc123.css` });
```

* `.js()` method added to match podlet and set own js

```js
layout.js({ value: `http://cdn.com/abc123abc123.js` });
```

* `.view()` method added to allow setting a template to use in the layout

```js
layout.view(data => `<html>...</html>`);
```

* `.render()` method added for framework implementors
```js
const incoming = new HttpIncoming(req, res, res.locals);
const result = layout.render(incoming, '<div>some content to render</div>');
```
* `.podiumSend()` method added for express users, this method matches the podiumSend method in the podlet
```js
app.get('/', (req, res) => {
    res.podiumSend({
        title: 'Custom page title',
        body: '<div>some content to render</div>',
    });
});
```

* `.middleware()` method changed to use new `.render()` method
* `.middleware()` method refactored to use async/await
* `.middleware()` method refactored to use the new `httpIncoming.proxy` flag

**Comment by trygve-lie** [comment]
In `@podium/client`:

 - Added a `state` event.
 - Added a `.state` property

We should deprecate the `change` and `dispose` events.

**Comment by trygve-lie** [comment]
In `@podium/schema` the schema has been rewritten from joi to a JSONSchema. For validation, there is added a set of helper validation methods.

In the schema the following is done:

 * `assets` is kept for backwards compabillity but deprecated and should not be used.
 * `js` and `css` is added at root of the schema and should be used instead of `assets`.

**Comment by digitalsadhu** [comment]
In `@podium/context`, `mountPathname` and `publicPathname` now use `util.pathnameBuilder` to construct URLs. In practice this means that publicPathname will no longer (ever) include a trailing slash. 

*IMPORTANT:* Users will need to ensure they are safely concatenating `ctx.mountOrigin`, `ctx.publicPathname` and any additional url segments or risk code breakage.
