### ISSUE TITLE
Passing undefined to podlet.fetch() should not be allowed

### ISSUE THREAD

**Issue by runarb** [podium-lib/issues#31]
When I did this it caused a podlet to load with an unexpected state which was very hard to troubleshoot. Would be nice if an error was thrown or at least logged.

**Comment by digitalsadhu** [comment]
Can you give an example? Did you pass a variable that turned out to be undefined?
Eg. 

```js
const something = functionThatReturnsUndefined();
await podlet.fetch(something);
```

The reason I ask is because I think the following is valid:

```js
await podlet.fetch();
```

In both cases the first argument to `fetch` is going to be `undefined` so I don't think we will be wanting to throw if that first argument is `undefined`. 

Is this your thinking @trygve-lie or do we want to make the first argument required?

**Comment by trygve-lie** [comment]
Currently its so that it's possible to pass an arbitrary object (a context) as the first argument to `.fetch()` and `.stream()`. In version 5 we want to remove this and make it so that the first argument could only be `HttpIncoming` and its required to pass in.

So; the plan is that it should be impossible to pass in `undefined` in version 5. Then, we should throw a clear exception if so is done.`

**Comment by digitalsadhu** [comment]
So that would make httpIncoming required? @trygve-lie

**Comment by trygve-lie** [comment]
This should be solved by https://github.com/podium-lib/client/pull/125 but do a check to see if this is actually the case.

**Comment by trygve-lie** [comment]
Can confirm that this is the case. https://github.com/podium-lib/client/pull/125 solves this.
