### ISSUE TITLE
Context locale doesn't work as expected

### ISSUE THREAD

**Issue by asgeirn** [podium-lib/issues#50]
According to https://podium-lib.io/docs/api/document#customizing the locale for the resulting HTML document is set using the `locale` attribute in `context`.

For one, the structure for configuring locale is not intuitive.  According to https://podium-lib.io/docs/api/layout#constructor and https://github.com/podium-lib/context#constructor, `layout` is an `object`, but the properties of this object is not immediately available.  Some code browsing reveals that the proper initialization is as follows:

```js
const layout = new Layout({
    // ....
    context: {
        locale: {
            locale: 'nb-NO'
        }
    }
});
```

Second, this locale value is not applied in the HTML template.  The cause appears to be the property naming in the HttpIncoming context.  The template expects the property `incoming.context.locale`, but the actual property turns out to be `incoming.context['podium-locale']`.

Are the parsed context properties misnamed?  Or what is the reasoning behind the `podium-` prefix?

**Comment by digitalsadhu** [comment]
There are a couple things going on here.

When working with a podlet, incoming.context.locale is correct, however, when working with a layout, the context has not been processed into the context object that you receive in a podlet and so the only option is to use the raw incoming.context['podium-locale'] value. [this PR](https://github.com/podium-lib/utils/pull/232) fixes the template so that it properly handles both cases. 

Secondly, there was a bug in the podlet where context values were not being parsed due to the params object not being set which is fixed in [this PR](https://github.com/podium-lib/podlet/pull/382).

Agree that the locale config is a little non intuitive there. Any change would be breaking and so is unlikely to be looked at until we do the next major version but worth keeping in mind for us to look at thanks.
